services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - THIRDWEB_SECRET_KEY=${THIRDWEB_SECRET_KEY}
      - THIRDWEB_CLIENT_ID=${THIRDWEB_CLIENT_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge 